### ISSUE TITLE
Plugin for NopCommerce 3.8

### ISSUE THREAD

**Issue by hitinder** [mobsoftware/mobSocial.nopCommercePlugin#4]
Instead of using the whole project can it be used as a plugin inside existing implementation of NopCommerce 3.8?

**Comment by wittyansh** [comment]
Hi,
Yes, that's what it is. This is actually the plugin for nopCommerce which you can compile and use for nopCommerce 3.8. We'd soon be making the release that's compatible with 3.8 version.

Unlike [standalone](https://github.com/mobsoftware/mobsocial) version, this requires nopCommerce for its functionality.

**Comment by hitinder** [comment]
So I can just compile the content of "Nop.Plugin.Widgets.mobSocial" and I can install it inside the NopCommerce site and I am good to go?

**Comment by wittyansh** [comment]
No, actually this is just the front end of the plugin. It relies on [WebApi](https://github.com/mobsoftware/mobsocial.webapi) plugin and [Core](https://github.com/mobsoftware/mob.core) library. So you'll need to download these projects as well. After that you can Compile the Widget plugin which in turn will compile both these plugins. This way, you will have two plugins on your nopCommerce plugin page, one for WebApi and one for Widget.

There is also a Suite plugin in this repository that use can compile as well. It collects files from all three projects and builds a single mobSocial plugin which automatically installs both webapi and widget plugins from nopCommerce dashboard. 

So if you happen to use Suite plugin, you'll only see on plugin in the dashboard and it acts as an installer for both the child plugins.
