### ISSUE TITLE
Issue accessing mobsocial after installation

### ISSUE THREAD

**Issue by PatelVish** [mobsoftware/mobSocial.nopCommercePlugin#6]
After I installed MobSocial plugins (both WebApi and MobSocial), when i try to access the mobsocial menu, none of the link works. Get error that api not found.

![image](https://cloud.githubusercontent.com/assets/2691184/26037135/3577edec-38bb-11e7-849d-0b6383ae439d.png)

Can you please tell me if i missed anything that was not mentioned in ReadMe.txt

**Comment by anshulsojatia** [comment]
Hi, if you are getting 404s that means the requests are not going through OWIN pipeline. Can you verify if AutomaticOwinStartup attribute is set to true if web.config file?

**Comment by vishalpatel-te-zz** [comment]
Awesome!!! That did the trick. It wasn't set. After i set  <add key="owin:AutomaticAppStartup" value="true" /> everything started working.
